TutorialCS/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DayPilot.Web.Mvc.Json;
using TutorialCS;
using TutorialCS.Models;
using System.Collections;
using TutorialCS.DataAccess;
using TutorialCS.Util;
using DayPilot.Web.Mvc.Recurrence;

public class EventController : Controller
{

    public ActionResult Edit(string id)
    {
        EditViewModel editView = new EditViewModel();
            var e = new EventManager().Get(id) ?? new EventManager.Event();
        Util util = new Util();
        TimeSpan test = e.End-e.Start;
        int diff = test.Days;

        editView.ID = e.Id;
        editView.Eventname = e.Text;
        editView.StartDate = e.Start;

        List<Employee> emplist = Session["emplist"] as List<Employee>;
        AbsenceDay Event = new AbsenceDay();



        foreach (var emp in emplist)
        { 
          var hol= emp.Events.Where(x => x.EventID == id);
            foreach (var realHol in hol)
            {
                Event = realHol;
            }
        }

        editView.ID = Event.EventID;
        editView.Eventname = Event.Description;
        editView.StartDate = Event.Start_Date;
        //if (diff ==1)
        //{
        //    editView.EndDate = e.End.AddDays(-1);
        //}
        //else
        //{
        editView.EndDate = Event.End_Date;
        //}

        editView.EmployeeName = e.Resource;
        var drop = util.GetRecurringList();
        editView.recurrDropList = util.GetRecurringList();
        editView.SelectedValue = EditViewModel.Selection.Option3;
        if (Event.recRule != null)
        {
            var rangeSpec = Event.recRule.RangeSpec;
            if (rangeSpec == RecurrenceRule.RangeSpecType.Times)
            {
                editView.recAmount = Event.recRule.TimesValue;
            }
            int index = 0;
            switch (Event.recRule.Repeat)
            {
                case RecurrenceRule.RepeatRule.Weekly:
                    if (Event.recRule.Every == 1)
                    {
                        index = 1;
                    }
                    else
                    {
                        index = 2;
                    }

                    break;
                case RecurrenceRule.RepeatRule.Daily:
                    index = 0;
                    break;
                case RecurrenceRule.RepeatRule.Annually:
                    index = 3;
                    break;
                default:
                    break;
            }
            editView.recurrDropList[index].Selected = true;
            //var test2 = e.Recurrence.Id;
        }


        return View(editView);
    }



    [AcceptVerbs(HttpVerbs.Post)]
    public ActionResult Edit(EditViewModel model)
    {
        DateTime start = Convert.ToDateTime(model.StartDate);
        DateTime end = Convert.ToDateTime(model.EndDate);
        new EventManager().EventEdit(model.ID, model.Eventname, start, end, model.EmployeeName);
        return JavaScript(SimpleJsonSerializer.Serialize("OK"));
    }


    public ActionResult Create()
    {
        Util util = new Util();
        CreateModel model = new CreateModel();
        List<Employee> emplist = Session["emplist"] as List<Employee>;

        List<Project> forChosen = new List<Project>();
        List<Employee> forChosenEmp = new List<Employee>();


  

        string id = Request.QueryString["resource"];
        model.SelectedEmployee = util.getEmployeeByID(id);
        model.SelectedEmployee.dispname = model.SelectedEmployee.EmployeeID + " " + model.SelectedEmployee.FirstName + " " + model.SelectedEmployee.LastName;


        model.StartDate = Convert.ToDateTime(Request.QueryString["start"]);
        model.EndDate = Convert.ToDateTime(Request.QueryString["end"]);

        //TimeSpan test = model.EndDate.Value - model.StartDate.Value;
        //int diff = test.Days;

        //if (diff>0)
        //{
        //    model.EndDate = model.EndDate.Value.AddDays(-1);
        //}
        //else
        //{
        //    model.EndDate = model.EndDate;
        //}


            foreach (var project in model.SelectedEmployee.Projects)
            {
              
                    forChosen.Add(project);
            }

        model.projectList = forChosen;
        model.projectDropList = prepareProjectTropdown(forChosen);

        model.employeeList = emplist;
        int index = emplist.IndexOf(model.SelectedEmployee);
        model.EmpDropDown = prepareEmpDropdown(model.employeeList);
        model.EmpDropDown[index].Selected = true;

        model.recurrDropList = util.GetRecurringList();
        Session["RecurrDrop"] = model.EmpDropDown;

        Session["EmpDropdown"] = model.EmpDropDown;
       

        Session["CreateProjectDropdown"] = model.projectDropList;



        return View(model);

    }
    public ActionResult CreateFromDropdown()
    {
        CreateFromProjectDropDownModel model = new CreateFromProjectDropDownModel();
        List<Employee> emplist = Session["emplist"] as List<Employee>;
        List<Employee> forChosen = new List<Employee>();
        Util util = new Util();

        string id = Request.QueryString["id"];
        
        model.SelectedProject = util.getProjectFromID(id);
        model.SelectedProject.dispName = model.SelectedProject.ProjectId + " " + model.SelectedProject.ProjectName;
        model.StartDate = null;
        model.EndDate = null;

        foreach (var emp in emplist)
        {
            foreach (var project in emp.Projects)
            {
                if (project.ProjectId == model.SelectedProject.ProjectId)
                {
                    forChosen.Add(emp);
                }
            }
        }
        
        model.employeeList = forChosen;
        model.EmpDropDown = prepareEmpDropdown(model.employeeList);
        Session["EmpDropdown"] = model.EmpDropDown;
        model.recurrDropList = util.GetRecurringList();
        


       // return View(new EventManager().makeEvent2(Request.QueryString["id"], Request.QueryString["start"], Request.QueryString["end"], Request.QueryString["resource"]));
        return View(model);
    }

    [HttpPost]
    public ActionResult CreateFromDropdown(CreateFromProjectDropDownModel model)
    {

        foreach (var item in model.SelectedID)
        {
            DAL_BYD dataAccess = new DAL_BYD();
            Util util = new Util();
            string empID = util.getEmpFromDropdown(item.ToString());
            string SAP_UUID = "";
            string[] buffer = empID.Split(' ');
            empID = buffer[0];


            DateTime start = Convert.ToDateTime(model.StartDate);
            DateTime end = Convert.ToDateTime(model.EndDate);


            string sStart = util.ConvertToABAPTime(model.StartDate.Value);
            string sEnd = util.ConvertToABAPTime(model.EndDate.Value);

            string[] buffer2 = model.SelectedProject.dispName.Split(' ');
            string projid = buffer2[0];
            string projname = "";
            for (int i = 1; i < buffer2.Length; i++)
            {
                projname = projname + buffer2[i] + " ";
            }

            DateTime sRecEnd = new DateTime();
            int recTimes = 0;
            bool unlimited = false;

            if (model.SelectedValue == Selection.Option1)
            {
                unlimited = true;
            }


            if (model.SelectedRecurrID != null)
            {
                string recType = util.getRecType(model.SelectedRecurrID[0]);

                switch (model.SelectedValue)
                {
                    case Selection.Option1:
                        break;
                    case Selection.Option2:
                        recTimes = getRecTimes(recType, (DateTime)model.StartDate, (DateTime)model.RecEndDate);
                        sRecEnd = (DateTime)model.RecEndDate;
                        break;
                    case Selection.Option3:
                        recTimes = model.recAmount;
                        break;
                    default:
                        break;
                }
                if (unlimited)
                {
                    SAP_UUID = dataAccess.SaveTimes(sStart, sEnd, projid, empID, recType, unlimited);
                }

                else
                {
                    SAP_UUID = dataAccess.SaveTimes(sStart, sEnd, projid, empID, recType, recTimes);
                }

                RecurrenceRule rule = null;
                switch (model.SelectedValue)
                {
                    case Selection.Option1:
                        rule = util.createRecRuleUnlimited(recType, start, SAP_UUID);
                        break;
                    case Selection.Option2:
                        rule = util.createRecRule(recType, start, (DateTime)model.RecEndDate, SAP_UUID);
                        break;
                    case Selection.Option3:
                        rule = util.createRecRuleTimes(recType, start, model.recAmount, SAP_UUID);
                        break;
                    default:
                        break;
                }
                new EventManager().EventCreate(start, end, projname, empID, SAP_UUID, rule);
            }
            else
            {
                SAP_UUID = dataAccess.SaveTimes(sStart, sEnd, projid, empID);
                new EventManager().EventCreate(start, end, projname, empID, SAP_UUID);

            }
        }
        return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }
   



    [HttpPost]
    public ActionResult Create(CreateModel model)
    {
        foreach (var item in model.SelectedID)
        {
            foreach (var item2 in model.SelectedEmpID)
            {
                DAL_BYD dataAccess = new DAL_BYD();
                Util util = new Util();

                string SAP_UUID = "";
                DateTime start = Convert.ToDateTime(model.StartDate);

TutorialCS/Controllers/SchedulerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DayPilot.Web.Mvc;
using DayPilot.Web.Mvc.Enums;
using DayPilot.Web.Mvc.Events.Scheduler;
using System.Drawing;
using DayPilot.Web.Mvc.Data;
using TutorialCS.Models;

namespace TutorialCS.Controllers
{
    public class SchedulerController : Controller
    {
        //
        // GET: /Scheduler/

        public ActionResult Backend()
        {
            return new Dps().CallBack(this);
        }

        class Dps : DayPilotScheduler
        {
            protected override void OnInit(InitArgs e)
            {
             
                LoadResources();
                //UpdateWithMessage("Welcome!", CallBackUpdateType.Full);
                Update(CallBackUpdateType.Full);
            }

            private void LoadResources()
            {
                foreach (DataRow r in new EventManager().GetResources().Rows)
                {
                    Resources.Add((string)r["name"], Convert.ToString(r["id"]));
                }
            }

            protected override void OnEventResize(EventResizeArgs e)
            {
                new EventManager().EventMove(e.Id, e.NewStart, e.NewEnd, e.Resource);
                UpdateWithMessage("The event was resized.");
            }

            protected override void OnEventMove(EventMoveArgs e)
            {
                new EventManager().EventMove(e.Id, e.NewStart, e.NewEnd, e.NewResource);
                UpdateWithMessage("The event was moved.");
            }

            protected override void OnTimeRangeSelected(TimeRangeSelectedArgs e)
            {
                if (CopyedEvent.eventRessource!= null && CopyedEvent.eventUUID != null)
                {
                    new EventManager().copyPaste(CopyedEvent.eventUUID, CopyedEvent.eventRessource, e.Resource, e.Start,CopyedEvent.TimeLenght);
         
                }
           
                UpdateWithMessage("A event was copied.");
            }
            protected override void OnEventMenuClick(EventMenuClickArgs e)
            {
                switch (e.Command)
                {
                    case "Delete":
                        new EventManager().EventDelete(e.Id);
                        Update();
                        break;
                    case "test":
                        var test = e;
                        
                        break;
                }
            }

            protected override void OnEventDoubleClick(EventDoubleClickArgs e)
            {
                CopyedEvent.eventUUID = e.Id;
                CopyedEvent.eventRessource = e.Resource;
                TimeSpan diff = e.End - e.Start;
                CopyedEvent.TimeLenght = diff.Days;
            }
            protected override void OnEventSelect(EventSelectArgs e)
            {
                var test = e;
            }
            protected override void OnEventDelete(EventDeleteArgs e)
            {
                string ID = "";
                if (e.Id != null ||e.RecurrentMasterId!= null) { 
                    if (e.Id ==null)
                    {
                        ID = e.RecurrentMasterId;
                        new EventManager().EventDelete(ID);
                    }

                   else
                    {
                        new EventManager().EventDelete(e.Id);
                    }
                }
                UpdateWithMessage("Event deleted.");
            }
            protected override void OnEventRightClick(EventRightClickArgs e)
            {
                CopyedEvent.eventUUID = e.Id;
                CopyedEvent.eventRessource = e.Resource;
            }

            protected override void OnCommand(CommandArgs e)
            {
                switch (e.Command)
                {
                    case "refresh":
                        UpdateWithMessage("Refreshed");
                        break;
                }
            }
            protected override void OnBeforeCellRender(BeforeCellRenderArgs e)
            {
                if (e.Start.DayOfWeek.ToString() =="Saturday" || e.Start.DayOfWeek.ToString() == "Sunday")
                {
                    e.BackgroundColor = "#d3d3d3";
                }
            }

            protected override void OnBeforeEventRender(BeforeEventRenderArgs e)
            {
                var test = e;
                var test2 = e.DataItem;
                var test3 = e.DataItem["name"];
                string buffer = test3.ToString();
               
                if (buffer.Contains("Abwesenheit"))
                {
                    e.BackgroundColor = "#ee5c42";
                    e.FontColor = "#FFFFFF";
                }
                else
                {
                    e.ContextMenuClientName = "menu";
                    int color = buffer.GetHashCode() & 0xFFFFFF;
                    string hex = color.ToString("X");
                    if (hex.Length<6)
                    {
                        for (int i = 0; i < 6-hex.Length; i++)
                        {
                            hex = "0" + hex;
                        }
                    }

                    hex = "#" + hex;

                    Color fromHex = Color.FromArgb(color);


                    // Counting the perceptive luminance - human eye favors green color... 
                    double a = 1 - (0.299 * fromHex.R + 0.587 * fromHex.G + 0.114 * fromHex.B) / 255;

                    if (a < 0.5) { 
                        e.FontColor = "#000000"; // bright colors - black font
                    }
                    else { 
                        e.FontColor = "#FFFFFF";
                    }
                   
                    e.BackgroundColor = hex;
                    if (e.RecurrentMasterId!= null)
                    {
                        e.BorderColor = "#000000";
                        
                    }
                    else
                    {
                        e.BorderColor = e.BackgroundColor;
                    }


                    e.Areas.Add(new Area().Width(17).Bottom(9).Right(2).Top(3).CssClass("event_action_menu").ContextMenu("menu"));
                }
                //if ((string)e.DataItem["type"] == "special")  // "type" field must be available in the DataSource
                //{
                //    e.CssClass = "special";
                //    e.BackgroundColor = "lightyellow";
                //    e.Html = "<i>WARNING: This is an unusual event.</i><br>" + e.Html;
                //}


                

                //e.Areas.Add(new Area().Width(17).Bottom(9).Right(2).Top(3).CssClass("event_action_delete").JavaScript("dps.eventDeleteCallBack(e);"));
            }

            protected override void OnFinish()
            {
                if (UpdateType == CallBackUpdateType.None)
                {
                    return;
                }

                Events = new EventManager().FilteredData(StartDate, StartDate.AddDays(Days)).AsEnumerable();

                DataIdField = "id";
                DataTextField = "name";
                DataStartField = "eventstart";
                DataEndField = "eventend";
                DataResourceField = "resource";
                DataTagFields= "tag";
                DataRecurrenceField = "recurrence";
            }

        }

    }
}

TutorialCS/Views/Home/Index.cshtml
@using DayPilot.Web.Mvc;
@using DayPilot.Web.Mvc.Events
@using DayPilot.Web.Mvc.Events.Scheduler;
@using DayPilot.Web.Mvc.Enums.Scheduler;

@model TutorialCS.Models.ViewModel



@{
    ViewBag.Title = "Übersicht";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<html>
<head>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.css">

    <script src="~/Scripts/chosen.jquery.js"></script>


   
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" />


</head>


<body>

<!-- Code for Calender Events -->
<script type="text/javascript">
function timeRangeSelected(start, end, resource) {
    var modal = new DayPilot.Modal();

  modal.top = 60;
  modal.width = 300;
  modal.opacity = 70;
  modal.border = "10px solid #d0d0d0";
  modal.closed = function() {
      if(this.result == "OK") {
          dps.commandCallBack('refresh');
      }
      dps.clearSelection();
  };

  //alert('test');
  var url = " @Url.Action("Create", "Event")"
    url += "?start=" + start.toStringSortable() + "&end=" + end.toStringSortable() + "&resource=" + resource;
   // alert('' + url);

    modal.showUrl(url);
}

/* Recurrence dialogs */
function ask(e) {
    //alert('' + e.name);
    // it's a normal event
    var serie = e.recurrent();
    if (serie==true) {
        var id = e.recurrentMasterId();
        e.data.id = id;
        edit(e);
        return;
    }
    if (!e.recurrent()) {
        if (e.data.text != "Abwesenheit") {
            edit(e);
            return;
        }
    return
    }
    
    // it's a recurrent event but it's an exception from the series
    if (e.value() !== null) {
        //alert('' + e.value);
        
        edit(e);
        return;
    }

    var modal = new DayPilot.Modal();
    modal.width = 300;
    modal.height = 150;
    alert('test');
    modal.closed = function () {
        if (this.result != "cancel") {
            edit(e, this.result);
        }
    };

    modal.showUrl('@Url.Action("RecurrentEditMode", "Event")');
}

    function test(e) {

        
    }

function edit(e, mode) {
    var modal = new DayPilot.Modal();
  
    modal.closed = function () {
        if (this.result === "OK") {
            dps.commandCallBack('refresh');
        }
    };

    var url = "@Url.Action("Edit", "Event")";
    if (e.id() !== null) {
        url += "/" + e.id();
    }
    url += "?";
   // alert('' + url);
    if (e.recurrentMasterId()) {
        url += "master=" + e.recurrentMasterId() + "&";
    }
    if (mode == "this") {
        url += "start=" + e.start().toStringSortable();
    }
    modal.showUrl(url);
}
    </script>



    <!-- Code to wire up your DatePicker -->
    <script type="text/javascript">
        $(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $('.date-picker').datepicker({
                changeMonth: true,
                changeYear: true,

                dateFormat: "dd M yy",

            });
        });
    </script>

  
    <script type="text/javascript">
     $(document).ready(function () {
            $(".chosen-select-multiple").chosen(
                {
                    disable_search_threshold: 10,
                    no_results_text: "Oops, nothing found!",
                    width: "100%",
                });
            $(".chosen-select-single").chosen(
                {
                    no_results_text: "Oops, nothing found!",
                    placeholder_text_single: "mittels Projekten",
                    width: "100%",
                }).change(function (event) {

                if (event.target == this) {
                    //alert($(this).val());
                }
                var id = $(this).val();


                var modal = new DayPilot.Modal();
                modal.top = 60;
                modal.width = 300;
                modal.opacity = 70;
                modal.border = "10px solid #d0d0d0";
                modal.closed = function() {
                    if(this.result == "OK") {
                        dps.commandCallBack('refresh');
                    }
                    dps.clearSelection();
                };

                var url = " @Url.Action("CreateFromDropdown", "Event")"
                url += "?id="+id+"&start=" + "" + "&end=" + "" + "&resource=" +"";
                modal.showUrl(url);

            });

        });
    </script>




    <div class="row jumbotron container-fluid text-center">
       

            <div class="col-lg-2">
                <img src="~/Media/pics/Wort-Bildmarke_4c.jpg" width="100%" />
            </div>
            <div class="col-lg-9">
                <div >
                    <h1>consus Personal Planung</h1>
                </div>
            </div>
        <div class="col-lg-1">

            @Html.ActionLink("Logout", "LogOut", "Home",null, new { @class = "btn btn-danger btn-sm" })
            
            </div>
        </div>



    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2">
				<div class="well well-sm">
					@using (Html.BeginForm())
					{
						<h4>Abteilungen</h4>
						@Html.HiddenFor(m => m.DepartDropDown)
						@Html.ListBoxFor(x => x.SelectedIds, Model.DepartDropDown, new { @class = "chosen-select-multiple form-control", style = "width:200px;" })
						<h4>Projekte</h4>
						@Html.HiddenFor(m => m.FilterProjectDropDown)
						@Html.ListBoxFor(x => x.FilterProjectSelectedID, Model.FilterProjectDropDown, new { @class = "chosen-select-multiple form-control", style = "width:200px;" })
						<br />
						<h4>anfang</h4>
						@Html.TextBoxFor(m => m.StartDate, new { @class = "date-picker form-control" })
						<h4>ende</h4>
						@Html.TextBoxFor(m => m.EndDate, new { @class = "date-picker  form-control" })
						<input type="submit" name="submit" value="refresh" class="btn btn-default">
					}
				</div>



                <div class="well well-sm">
                    <h4>Neues Event</h4>
                    @Html.DropDownListFor(x => x.ProjectSelectedID, Model.ProjectDropDown, new { @class = "chosen-select-single form-control", @multiple=false, style = "width:200px;" })
                </div>
            </div>

            <div class="col-lg-10">
                @Html.DayPilotMenu("menu", new DayPilotMenuConfig
           {
               Theme = "menu_default",
               Items = new MenuItemCollection
                   {
                        new MenuItem { Text = "Öffnen", Action = DayPilot.Web.Mvc.Enums.MenuItemAction.JavaScript, JavaScript = "ask(e);"},
                        new MenuItem { Text = "Löschen", Action = DayPilot.Web.Mvc.Enums.MenuItemAction.JavaScript, JavaScript = "if (confirm('Sind Sie sicher,dass Sie diese Abwesenheit löschen wollen?')) { dps.eventDeleteCallBack(e); }"},
                        new MenuItem { Text = "Copy", Action = DayPilot.Web.Mvc.Enums.MenuItemAction.JavaScript, JavaScript = "dps.eventDoubleClickCallBack(e);" },
                        
                    }
                })

                @Html.DayPilotMenu("menu_selection", new DayPilotMenuConfig
                {
                    Items = new DayPilot.Web.Mvc.MenuItemCollection
                    {
                        new MenuItem { Text = "Einfügen", Action = DayPilot.Web.Mvc.Enums.MenuItemAction.JavaScript, JavaScript="dps.timeRangeSelectedCallBack(this.source.start, this.source.end, this.source.resource);" }
                    }
                })

                @Html.DayPilotScheduler("dps", new DayPilotSchedulerConfig
                {
                   BackendUrl = Url.Action("Backend", "Scheduler"),


                   CellGroupBy = DayPilot.Web.Mvc.Enums.GroupBy.Month,
                   CellDuration = 1440,

                   Days = Convert.ToInt16(Session["EndDate"]),
                   StartDate = Convert.ToDateTime(Session["StartDate"]),

                   EventEndSpec=DayPilot.Web.Mvc.Enums.DateTimeSpec.Date,
                   CellWidthSpec = (CellWidthSpec)(Session["AutoWidth"]),

                   Crosshair = CrosshairType.Full,

                   Theme = "scheduler_white",
                   EventHeight = 25,
                   CellWidth = 50,

                   TimeHeaders = new TimeHeaderCollection
                        {
                            new TimeHeader { GroupBy =DayPilot.Web.Mvc.Enums.GroupBy.Month, Format = "MMMM yyyy"},
                            new TimeHeader { GroupBy = DayPilot.Web.Mvc.Enums.GroupBy.Day, Format = "ddd. dd"}
                        },

                   RowMarginBottom = 15,
                   RowMarginTop = 5,
                   //RowMinHeight = 60,

                   MoveBy = DragArea.Full,

                  // ContextMenu = "menu",
                   ContextMenuSelection="menu_selection",
               
                   EventResizeHandling = EventResizeHandlingType.CallBack,
                   EventMoveHandling = EventMoveHandlingType.Notify,

                   EventRightClickHandling = EventRightClickHandlingType.ContextMenu,
               
                   EventClickHandling = EventClickHandlingType.JavaScript,
                   EventClickJavaScript = "ask(e);",

                   TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
                   TimeRangeSelectedJavaScript = "timeRangeSelected(start, end, resource);",

               })

            </div>

         

            <div class="col-lg-1">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">

            </div>
            <div class="col-lg-10">

            </div>
        </div>
    </div>
</body>

</html>